### ISSUE TITLE
Feature: proper RedHat Support

### ISSUE THREAD

**Issue by dschier-wtd** [while-true-do/ansible-role-srv_cockpit#7]
According to the RedHat Doumentation some extra steps are needed:

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html-single/getting_started_with_cockpit/index

**Comment by daniel-schier** [comment]
rhel's cockpit does not support the following packages:

- cockpit-kdump
- cockpit-selinux
- cockpit-sosreport
- cockpit-networkmanager
